import type { Metadata } from 'next'
import { Roboto_Flex as Roboto, Bai_Jamjuree as BaiJamjure } from 'next/font/google'
import './globals.css'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto'})
const baijamjure = BaiJamjure({ subsets: ['latin'], weight: '700', variable: '--font-baijamjure' })

export const metadata: Metadata = {
  title: 'NWL Timeline',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${baijamjure.variable} font-sans text-gray-100 bg-gray-900`}>{children}</body>
    </html>
  )
}
